### ISSUE TITLE
Seems not to work with @BindView annotation from Butterknife 8.1.0

### ISSUE THREAD

**Issue by SimonHaenle2** [dpreussler/Diacetyl#4]
Hey Danny, 
sorry it's me again :)
So I've tried this with Butterknife 8.1.0 and the @BindView Annotation. However, when I try to run the test, i get:

java.lang.NullPointerException
    at butterknife.internal.Finder.getResourceEntryName(Finder.java:131)
    at butterknife.internal.Finder$1.getResourceEntryName(Finder.java:25)
    at butterknife.internal.Finder.findRequiredView(Finder.java:70)
    at com.daimler.mm.android.location.parking.ParkingDetailsView$$ViewBinder$InnerUnbinder.<init>(ParkingDetailsView$$ViewBinder.java:25)
    at com.mm.android.location.parking.ParkingDetailsView$$ViewBinder.bind(ParkingDetailsView$$ViewBinder.java:16)
    at com.mm.android.location.parking.ParkingDetailsView$$ViewBinder.bind(ParkingDetailsView$$ViewBinder.java:13)
    at butterknife.ButterKnife.bind(ButterKnife.java:133)

Any ideas?
Best Regards,
Simon

**Comment by dpreussler** [comment]
oh you have to make sure you are not calling Butterknife.bind in your tests.
Diacetyl does not touch this (maybe could do some static magic in future but not easy).
So just wrap the Butterknife.bind call into a Viewbinder class that you can disable in tests, i showed an example in the presentation.
Or simple for now: make it a package protected method

void bind() {
   Butterknife.bind(this);
}

and then in test you simply override it

ParkingDetailsView tested = new ParkingDetailsView(...) {
   @Override 
   void bind() {
     Diacetyl.butterForTests(this)
  }
...
